name: Node CI

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: latest
    - name: npm install and lint
      run: |
        npm install
        npm run lint
      env:
        CI: true
